### ISSUE TITLE
v1.11.x Send page unresponsive

### ISSUE THREAD

**Issue by mezuny** [Tastenkunst/eternl-tracker#101]
Errors could include;
Lead: ErrorBuildTx.valueToLow.0
Lead: ErrorBuildTx.missingAddress.0 < Timing issue in rare cases / devices with poor performance?

**Comment by Scitz0** [comment]
Should be fixed by [#114](https://github.com/Tastenkunst/eternl-tracker/issues/114)

**Comment by Scitz0** [comment]
Send page improved in 1.12
