### ISSUE TITLE
v1.11.x - Error for reference scripts inputs on ordinary transaction

### ISSUE THREAD

**Issue by mezuny** [Tastenkunst/eternl-tracker#107]
![image](https://github.com/Tastenkunst/eternl-tracker/assets/4470326/b2008bed-08e1-4fb6-a17f-e7ec1421312c)
reference inputs not allowed in TransactionSigningMode.ORDINARY_TRANSACTION

**Comment by Scitz0** [comment]
Working correctly in 1.12 to my knowledge
