### ISSUE TITLE
v.1.11.x - show nicer aux mismatch warning if no aux data provided

### ISSUE THREAD

**Issue by Scitz0** [Tastenkunst/eternl-tracker#118]
It was requested to not show aux hash mismatch in certain situations. The example provided was:
> But for allot of us using multisig minting, we do this intentionally. This is to hide the metadata pre-mint.

I propose to keep current message if aux data is provided but doesn't match. If however no aux data is provided but there is a hash in the body, show a "nicer" message like: `Metadata included in the transaction but DApp has decided to not provide it.`

**Comment by mezuny** [comment]
Now defaults to `Transaction metadata is hidden.`. Need @Scitz0 to take a look / take a look together to split the error reporting in to mismatch OR hidden

**Comment by Scitz0** [comment]
Implemented in 1.12
