### ISSUE TITLE
v1.11 - Show what key is requested to sign a signData request

### ISSUE THREAD

**Issue by mezuny** [Tastenkunst/eternl-tracker#130]

**Comment by mezuny** [comment]
Additionally, potentially add support for UTF16 encoded text, not just UTF8
![image](https://github.com/Tastenkunst/eternl-tracker/assets/4470326/131ed63e-bd66-45e3-868d-9d76a60f8adc)

![image](https://github.com/Tastenkunst/eternl-tracker/assets/4470326/6b346b57-7a32-4894-a692-99abd717b38b)

**Comment by mezuny** [comment]
![Image](https://github.com/Tastenkunst/eternl-tracker/assets/4470326/0c9a5a30-92e1-45ff-905a-51d41882b554)

**Comment by mezuny** [comment]
Also add a visualization for origin of request, maybe base url of tab calling signData

**Comment by mezuny** [comment]
Pushed to #add-eternl-core-mark on commit 487f5d9e

**Comment by Scitz0** [comment]
Fixed in 1.12
