### ISSUE TITLE
v1.11 - ADAHandle lookup fails / gets stuck

### ISSUE THREAD

**Issue by mezuny** [Tastenkunst/eternl-tracker#139]
Hey team, I cant resolve any handles - tried with the upgraded handles and the default ones

![image](https://github.com/Tastenkunst/eternl-tracker/assets/4470326/16d172c3-4312-4477-9be0-5ee3955d0848)

**Comment by mezuny** [comment]
![image](https://github.com/Tastenkunst/eternl-tracker/assets/4470326/0c1fffab-c4d9-473a-8921-4b49d64e5b11)

**Comment by Scitz0** [comment]
No issues in v1.12 to my knowledge, re-open if needed.
