### ISSUE TITLE
v1.11 - GetUtxos returns null

### ISSUE THREAD

**Issue by mezuny** [Tastenkunst/eternl-tracker#142]
![image](https://github.com/Tastenkunst/eternl-tracker/assets/4470326/85f616a9-f595-4cb2-8424-f8cf21527122)

acct_xvk1gj68t96gc4fhhtalyhhpprcngtu785kd38t4pnh2p9gs4m6e8ge93sgrhcjgjzmxvwmn0ljhcx6zywka4d5tag2k95xkj42d0pfmz4c4x064d

Go to https://city.theapesociety.io/crafting
Click 'Claim' on the option available (user will likely claim this as is). To preserve wallet state, I have a JSON locally of the read-only account.

**Comment by mezuny** [comment]
User did TX with Nami and worked
ad6cb3dff6cb3d68761be59356c49d468c69ef3b8416fd241b73fecc50776e8e

User has a stamped TAS Passport, potential lead

**Comment by Scitz0** [comment]
Fixed in 1.12
