### ISSUE TITLE
v1.11 - Transaction building error'ing

### ISSUE THREAD

**Issue by mezuny** [Tastenkunst/eternl-tracker#144]
acct_xvk1588lhdg9sqrfcer89gw6hwzcy5whtpah0p956m5sxtsja7x9784q48wtd4m56xc7l8unv37uld22fz7qaq5pj96pzddj4ucwx64rh8g5kn7zy

Go to send
Add recipient
Add all tokens
Add all ADA through max
Expected behavior: Errors in console + Waiting for input flashing the desired output and back to 0

**Comment by Scitz0** [comment]
Fixed in 1.12
