### ISSUE TITLE
When importing a HW export, make sure to persist HID connection and/or prompt user to pair again

### ISSUE THREAD

**Issue by mezuny** [Tastenkunst/eternl-tracker#148]
User report:
One more for the knowledge base.  I reported it earlier, but forgot about it, and post the application reset was also confused on what was happening when my hardware wallet didn't work.  If someone resets and then just imports old wallets, they lose the HID connection, and it is confusing what is going wrong.

If one tries to create a new account with a hardware wallet, even a preexisting one, it clears it.

It would be good if there was a way to avoid this or a note to the user to reconnect post reset.

**Comment by Scitz0** [comment]
New Ledger USB handling implemented
