### ISSUE TITLE
v1.11.0 - SAM address error

### ISSUE THREAD

**Issue by Scitz0** [Tastenkunst/eternl-tracker#26]
havealoha — Today at 03:06
Error trying to set sam.
I think that address doesnt belong to that stake key but a more informative error would be nice
![Image](https://github.com/Tastenkunst/eternl-tracker/assets/15903629/38f7f1e0-3e07-4a04-b913-6492b12560c9)

**Comment by mezuny** [comment]
Likely testnet related? Not reproduceable on mainnet, gives proper error

**Comment by Scitz0** [comment]
Yeah cant reproduce either, I'll mark it as invalid
