### ISSUE TITLE
How does the wallet check transaction validity?

### ISSUE THREAD

**Issue by klntsky** [Tastenkunst/eternl-tracker#89]
What is the algorithm that determines if the wallet is able to sign the transaction? As far as I understand, Eternl does a few more steps than other wallets when showing a signature popup - in particular, it verifies if the UTxOs are real and refuses to sign if not. What other checks does it perform? Does it check the tx for being properly balanced? Does it perform L2 validation?

**Comment by Scitz0** [comment]
Sorry for the VERY late reply, really embarrassed about that, better late than never I guess.

Eternl does a few things like you mention. We parse the tx to check what signatures are needed to sign the transaction. From this we determine what signatures (keys) the currently selected account can sign/witness. We can then either fully or partially sign the transaction. 

Like you mention, we also do not allow unknown utxo inputs. The reason for this is that we want to be able to show whats leaving the account to prevent tricking user to sign something that will drain their wallet. For this we track all utxo's on chain, whats been submitted but not on chain previously through Eternl (users local instance), as well as signed but not submitted through Eternl. We have plans to also monitor a global mempool to extend the possibility to catch unknown utxos. 

We do not however do any tx balance check that inputs match outputs (caught on submission) or L2 validation.

**Comment by Scitz0** [comment]
I'll close the issue with this reply.
